//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLToolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLToolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet must be initialized before calling Update routine. Cannot update database from a null dataset..
        /// </summary>
        internal static string DbManager_CannotUpdateNullDataset {
            get {
                return ResourceManager.GetString("DbManager_CannotUpdateNullDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable must be initialized before calling Update routine. Cannot update database from a null data table..
        /// </summary>
        internal static string DbManager_CannotUpdateNullDataTable {
            get {
                return ResourceManager.GetString("DbManager_CannotUpdateNullDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection does not match the data provider type..
        /// </summary>
        internal static string DbManager_ConnectionTypeMismatch {
            get {
                return ResourceManager.GetString("DbManager_ConnectionTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataProvider.ConnectionType must be a valid connection type.
        /// </summary>
        internal static string DbManager_InvalidDataProviderConnectionType {
            get {
                return ResourceManager.GetString("DbManager_InvalidDataProviderConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataProvider.Name must be a valid string.
        /// </summary>
        internal static string DbManager_InvalidDataProviderName {
            get {
                return ResourceManager.GetString("DbManager_InvalidDataProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataProvider.ProviderName must be a valid string.
        /// </summary>
        internal static string DbManager_InvalidDataProviderProviderName {
            get {
                return ResourceManager.GetString("DbManager_InvalidDataProviderProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to providerName must be a valid string.
        /// </summary>
        internal static string DbManager_InvalidProviderName {
            get {
                return ResourceManager.GetString("DbManager_InvalidProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter count does not match Parameter Value count..
        /// </summary>
        internal static string DbManager_MismatchParameterCount {
            get {
                return ResourceManager.GetString("DbManager_MismatchParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only objects of type IDbDataParameter or arrays of IDbDataParameter are supported.
        /// </summary>
        internal static string DbManager_NotDbDataParameter {
            get {
                return ResourceManager.GetString("DbManager_NotDbDataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; key does not exist in the configuration file..
        /// </summary>
        internal static string DbManager_UnknownConfiguration {
            get {
                return ResourceManager.GetString("DbManager_UnknownConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type of the connection could not be recognized..
        /// </summary>
        internal static string DbManager_UnknownConnectionType {
            get {
                return ResourceManager.GetString("DbManager_UnknownConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A suitable data provider is not available for configuration &apos;{0}&apos;..
        /// </summary>
        internal static string DbManager_UnknownDataProvider {
            get {
                return ResourceManager.GetString("DbManager_UnknownDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to query type &apos;{0}&apos; for method &apos;{1}&apos;..
        /// </summary>
        internal static string EmitHelper_NoSuchMethod {
            get {
                return ResourceManager.GetString("EmitHelper_NoSuchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not expected..
        /// </summary>
        internal static string EmitHelper_NotExpectedType {
            get {
                return ResourceManager.GetString("EmitHelper_NotExpectedType", resourceCulture);
            }
        }
    }
}
