//--------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------
using System;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;

namespace Templates
{
	public partial class DataModel : DbManager
	{
		public Table<BinaryData>    BinaryData    { get { return GetTable<BinaryData>();    } }
		public Table<Child>         Child         { get { return GetTable<Child>();         } }
		public Table<DataTypeTest>  DataTypeTest  { get { return GetTable<DataTypeTest>();  } }
		public Table<Doctor>        Doctor        { get { return GetTable<Doctor>();        } }
		public Table<GrandChild>    GrandChild    { get { return GetTable<GrandChild>();    } }
		public Table<LinqDataTypes> LinqDataTypes { get { return GetTable<LinqDataTypes>(); } }
		public Table<Parent>        Parent        { get { return GetTable<Parent>();        } }
		public Table<Patient>       Patient       { get { return GetTable<Patient>();       } }
		public Table<Person>        Person        { get { return GetTable<Person>();        } }
	}

	[TableName(Owner="dbo", Name="BinaryData")]
	public partial class BinaryData
	{
		public int BinaryDataID;
		public int Stamp;
		public int Data;
	}

	[TableName(Owner="dbo", Name="Child")]
	public partial class Child
	{
		public int ParentID;
		public int ChildID;
	}

	[TableName(Owner="dbo", Name="DataTypeTest")]
	public partial class DataTypeTest
	{
		public int DataTypeID;
		public int Binary_;
		public int Boolean_;
		public int Byte_;
		public int Bytes_;
		public int Char_;
		public int DateTime_;
		public int Decimal_;
		public int Double_;
		public int Guid_;
		public int Int16_;
		public int Int32_;
		public int Int64_;
		public int Money_;
		public int SByte_;
		public int Single_;
		public int Stream_;
		public int String_;
		public int UInt16_;
		public int UInt32_;
		public int UInt64_;
		public int Xml_;
	}

	[TableName(Owner="dbo", Name="Doctor")]
	public partial class Doctor
	{
		public int PersonID;
		public int Taxonomy;
	}

	[TableName(Owner="dbo", Name="GrandChild")]
	public partial class GrandChild
	{
		public int ParentID;
		public int ChildID;
		public int GrandChildID;
	}

	[TableName(Owner="dbo", Name="LinqDataTypes")]
	public partial class LinqDataTypes
	{
		public int ID;
		public int MoneyValue;
		public int DateTimeValue;
		public int BoolValue;
		public int GuidValue;
		public int BinaryValue;
		public int SmallIntValue;
	}

	[TableName(Owner="dbo", Name="Parent")]
	public partial class Parent
	{
		public int ParentID;
		public int Value1;
	}

	[TableName(Owner="dbo", Name="Patient")]
	public partial class Patient
	{
		public int PersonID;
		public int Diagnosis;
	}

	[TableName(Owner="dbo", Name="Person")]
	public partial class Person
	{
		public int PersonID;
		public int FirstName;
		public int LastName;
		public int MiddleName;
		public int Gender;
	}
}
