BLToolkitData.dbo.BinaryData, 1, BinaryDataID
BLToolkitData.dbo.BinaryData, 1, BinaryDataID
BLToolkitData.dbo.BinaryData, 2, Stamp
BLToolkitData.dbo.BinaryData, 3, Data
BLToolkitData.dbo.Child, 1, ParentID
BLToolkitData.dbo.Child, 1, ParentID
BLToolkitData.dbo.Child, 2, ChildID
BLToolkitData.dbo.Child, 2, ChildID
BLToolkitData.dbo.DataTypeTest, 1, DataTypeID
BLToolkitData.dbo.DataTypeTest, 1, DataTypeID
BLToolkitData.dbo.DataTypeTest, 2, Binary_
BLToolkitData.dbo.DataTypeTest, 3, Boolean_
BLToolkitData.dbo.DataTypeTest, 4, Byte_
BLToolkitData.dbo.DataTypeTest, 5, Bytes_
BLToolkitData.dbo.DataTypeTest, 6, Char_
BLToolkitData.dbo.DataTypeTest, 7, DateTime_
BLToolkitData.dbo.DataTypeTest, 8, Decimal_
BLToolkitData.dbo.DataTypeTest, 9, Double_
BLToolkitData.dbo.DataTypeTest, 10, Guid_
BLToolkitData.dbo.DataTypeTest, 11, Int16_
BLToolkitData.dbo.DataTypeTest, 12, Int32_
BLToolkitData.dbo.DataTypeTest, 12, Int32_
BLToolkitData.dbo.DataTypeTest, 13, Int64_
BLToolkitData.dbo.DataTypeTest, 14, Money_
BLToolkitData.dbo.DataTypeTest, 15, SByte_
BLToolkitData.dbo.DataTypeTest, 16, Single_
BLToolkitData.dbo.DataTypeTest, 17, Stream_
BLToolkitData.dbo.DataTypeTest, 18, String_
BLToolkitData.dbo.DataTypeTest, 18, String_
BLToolkitData.dbo.DataTypeTest, 19, UInt16_
BLToolkitData.dbo.DataTypeTest, 20, UInt32_
BLToolkitData.dbo.DataTypeTest, 20, UInt32_
BLToolkitData.dbo.DataTypeTest, 21, UInt64_
BLToolkitData.dbo.DataTypeTest, 22, Xml_
BLToolkitData.dbo.Doctor, 1, PersonID
BLToolkitData.dbo.Doctor, 1, PersonID
BLToolkitData.dbo.Doctor, 2, Taxonomy
BLToolkitData.dbo.Doctor, 2, Taxonomy
BLToolkitData.dbo.DoctorView, 1, PersonID
BLToolkitData.dbo.DoctorView, 1, PersonID
BLToolkitData.dbo.DoctorView, 2, Taxonomy
BLToolkitData.dbo.DoctorView, 2, Taxonomy
BLToolkitData.dbo.GrandChild, 1, ParentID
BLToolkitData.dbo.GrandChild, 1, ParentID
BLToolkitData.dbo.GrandChild, 2, ChildID
BLToolkitData.dbo.GrandChild, 2, ChildID
BLToolkitData.dbo.GrandChild, 3, GrandChildID
BLToolkitData.dbo.GrandChild, 3, GrandChildID
BLToolkitData.dbo.LinqDataTypes, 1, ID
BLToolkitData.dbo.LinqDataTypes, 1, ID
BLToolkitData.dbo.LinqDataTypes, 2, MoneyValue
BLToolkitData.dbo.LinqDataTypes, 3, DateTimeValue
BLToolkitData.dbo.LinqDataTypes, 4, BoolValue
BLToolkitData.dbo.LinqDataTypes, 5, GuidValue
BLToolkitData.dbo.LinqDataTypes, 6, BinaryValue
BLToolkitData.dbo.LinqDataTypes, 7, SmallIntValue
BLToolkitData.dbo.Parent, 1, ParentID
BLToolkitData.dbo.Parent, 1, ParentID
BLToolkitData.dbo.Parent, 2, Value1
BLToolkitData.dbo.Parent, 2, Value1
BLToolkitData.dbo.Patient, 1, PersonID
BLToolkitData.dbo.Patient, 1, PersonID
BLToolkitData.dbo.Patient, 2, Diagnosis
BLToolkitData.dbo.Patient, 2, Diagnosis
BLToolkitData.dbo.Person, 1, PersonID
BLToolkitData.dbo.Person, 1, PersonID
BLToolkitData.dbo.Person, 2, FirstName
BLToolkitData.dbo.Person, 2, FirstName
BLToolkitData.dbo.Person, 3, LastName
BLToolkitData.dbo.Person, 3, LastName
BLToolkitData.dbo.Person, 4, MiddleName
BLToolkitData.dbo.Person, 4, MiddleName
BLToolkitData.dbo.Person, 5, Gender
1, DataTypeID
1, DataTypeID
2, Binary_
3, Boolean_
4, Byte_
5, Bytes_
6, Char_
7, DateTime_
8, Decimal_
9, Double_
10, Guid_
11, Int16_
12, Int32_
12, Int32_
13, Int64_
14, Money_
15, SByte_
16, Single_
17, Stream_
18, String_
18, String_
19, UInt16_
20, UInt32_
20, UInt32_
21, UInt64_
22, Xml_
1, ID
1, ID
2, MoneyValue
3, DateTimeValue
4, BoolValue
5, GuidValue
6, BinaryValue
7, SmallIntValue
1, PersonID
1, PersonID
2, FirstName
2, FirstName
3, LastName
3, LastName
4, MiddleName
4, MiddleName
5, Gender
1, PersonID
1, PersonID
2, Taxonomy
2, Taxonomy
1, PersonID
1, PersonID
2, Diagnosis
2, Diagnosis
1, BinaryDataID
1, BinaryDataID
2, Stamp
3, Data
1, ParentID
1, ParentID
2, ChildID
2, ChildID
3, GrandChildID
3, GrandChildID
1, PersonID
1, PersonID
2, Taxonomy
2, Taxonomy
1, ParentID
1, ParentID
2, Value1
2, Value1
1, ParentID
1, ParentID
2, ChildID
2, ChildID
//--------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------
using System;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;

namespace Templates
{
	public partial class Test : DbManager
	{
		public Table<BinaryData>    BinaryData    { get { return GetTable<BinaryData>();    } }
		public Table<Child>         Child         { get { return GetTable<Child>();         } }
		public Table<DataTypeTest>  DataTypeTest  { get { return GetTable<DataTypeTest>();  } }
		public Table<Doctor>        Doctor        { get { return GetTable<Doctor>();        } }
		public Table<DoctorView>    DoctorView    { get { return GetTable<DoctorView>();    } }
		public Table<GrandChild>    GrandChild    { get { return GetTable<GrandChild>();    } }
		public Table<LinqDataTypes> LinqDataTypes { get { return GetTable<LinqDataTypes>(); } }
		public Table<Parent>        Parent        { get { return GetTable<Parent>();        } }
		public Table<Patient>       Patient       { get { return GetTable<Patient>();       } }
		public Table<Person>        Person        { get { return GetTable<Person>();        } }
	}

	[TableName(Owner="dbo", Name="BinaryData")]
	public partial class BinaryData
	{
	}

	[TableName(Owner="dbo", Name="Child")]
	public partial class Child
	{
	}

	[TableName(Owner="dbo", Name="DataTypeTest")]
	public partial class DataTypeTest
	{
	}

	[TableName(Owner="dbo", Name="Doctor")]
	public partial class Doctor
	{
	}

	[TableName(Owner="dbo", Name="DoctorView")]
	public partial class DoctorView
	{
	}

	[TableName(Owner="dbo", Name="GrandChild")]
	public partial class GrandChild
	{
	}

	[TableName(Owner="dbo", Name="LinqDataTypes")]
	public partial class LinqDataTypes
	{
	}

	[TableName(Owner="dbo", Name="Parent")]
	public partial class Parent
	{
	}

	[TableName(Owner="dbo", Name="Patient")]
	public partial class Patient
	{
	}

	[TableName(Owner="dbo", Name="Person")]
	public partial class Person
	{
	}
}
