
//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;
using BLToolkit.Mapping;

namespace Templates.MSSql
{
	public partial class MSSqlDataModel : DbManager
	{
		public Table<BinaryDatum>  BinaryData    { get { return this.GetTable<BinaryDatum>();  } }
		public Table<Child>        Children      { get { return this.GetTable<Child>();        } }
		public Table<DataType>     DataTypes     { get { return this.GetTable<DataType>();     } }
		public Table<DataTypeTest> DataTypeTests { get { return this.GetTable<DataTypeTest>(); } }
		public Table<Doctor>       Doctors       { get { return this.GetTable<Doctor>();       } }
		public Table<GrandChild>   GrandChildren { get { return this.GetTable<GrandChild>();   } }
		public Table<LinqDataType> LinqDataTypes { get { return this.GetTable<LinqDataType>(); } }
		public Table<Parent>       Parents       { get { return this.GetTable<Parent>();       } }
		public Table<Patient>      Patients      { get { return this.GetTable<Patient>();      } }
		public Table<Person>       People        { get { return this.GetTable<Person>();       } }
	}

	[Serializable, DataContract]
	[TableName(Name="BinaryData")]
	public partial class BinaryDatum
	{
		[Identity, PrimaryKey(1), DataMember] public int    BinaryDataID { get; set; }
		[                         DataMember] public byte[] Stamp        { get; set; }
		[                         DataMember] public byte[] Data         { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="Child")]
	public partial class Child
	{
		[Nullable, DataMember] public int? ParentID { get; set; }
		[Nullable, DataMember] public int? ChildID  { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="DataTypes")]
	public partial class DataType
	{
		[Nullable, DataMember] public int?     ID         { get; set; }
		[Nullable, DataMember] public decimal? MoneyValue { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="DataTypeTest")]
	public partial class DataTypeTest
	{
		[Identity, PrimaryKey(1), DataMember] public int       DataTypeID { get; set; }
		[Nullable,                DataMember] public byte[]    Binary_    { get; set; }
		[Nullable,                DataMember] public bool?     Boolean_   { get; set; }
		[Nullable,                DataMember] public byte?     Byte_      { get; set; }
		[Nullable,                DataMember] public byte[]    Bytes_     { get; set; }
		[Nullable,                DataMember] public char?     Char_      { get; set; }
		[Nullable,                DataMember] public DateTime? DateTime_  { get; set; }
		[Nullable,                DataMember] public decimal?  Decimal_   { get; set; }
		[Nullable,                DataMember] public double?   Double_    { get; set; }
		[Nullable,                DataMember] public Guid?     Guid_      { get; set; }
		[Nullable,                DataMember] public short?    Int16_     { get; set; }
		[Nullable,                DataMember] public int?      Int32_     { get; set; }
		[Nullable,                DataMember] public long?     Int64_     { get; set; }
		[Nullable,                DataMember] public decimal?  Money_     { get; set; }
		[Nullable,                DataMember] public byte?     SByte_     { get; set; }
		[Nullable,                DataMember] public float?    Single_    { get; set; }
		[Nullable,                DataMember] public byte[]    Stream_    { get; set; }
		[Nullable,                DataMember] public string    String_    { get; set; }
		[Nullable,                DataMember] public short?    UInt16_    { get; set; }
		[Nullable,                DataMember] public int?      UInt32_    { get; set; }
		[Nullable,                DataMember] public long?     UInt64_    { get; set; }
		[Nullable,                DataMember] public string    Xml_       { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="Doctor")]
	public partial class Doctor
	{
		[PrimaryKey(1), DataMember] public int    PersonID { get; set; }
		[               DataMember] public string Taxonomy { get; set; }

		// FK_Doctor_Person
		[Association(ThisKey="PersonID", OtherKey="PersonID", CanBeNull=false)]
		public Person Person { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="GrandChild")]
	public partial class GrandChild
	{
		[Nullable, DataMember] public int? ParentID     { get; set; }
		[Nullable, DataMember] public int? ChildID      { get; set; }
		[Nullable, DataMember] public int? GrandChildID { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="LinqDataTypes")]
	public partial class LinqDataType
	{
		[Nullable, DataMember] public int?      ID            { get; set; }
		[Nullable, DataMember] public decimal?  MoneyValue    { get; set; }
		[Nullable, DataMember] public DateTime? DateTimeValue { get; set; }
		[Nullable, DataMember] public bool?     BoolValue     { get; set; }
		[Nullable, DataMember] public Guid?     GuidValue     { get; set; }
		[Nullable, DataMember] public byte[]    BinaryValue   { get; set; }
		[Nullable, DataMember] public short?    SmallIntValue { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="Parent")]
	public partial class Parent
	{
		[Nullable, DataMember] public int? ParentID { get; set; }
		[Nullable, DataMember] public int? Value1   { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="Patient")]
	public partial class Patient
	{
		[PrimaryKey(1), DataMember] public int    PersonID  { get; set; }
		[               DataMember] public string Diagnosis { get; set; }

		// FK_Patient_Person
		[Association(ThisKey="PersonID", OtherKey="PersonID", CanBeNull=false)]
		public Person Person { get; set; }
	}

	[Serializable, DataContract]
	[TableName(Name="Person")]
	public partial class Person
	{
		[Identity, PrimaryKey(1), DataMember] public int    PersonID   { get; set; }
		[                         DataMember] public string FirstName  { get; set; }
		[                         DataMember] public string LastName   { get; set; }
		[Nullable,                DataMember] public string MiddleName { get; set; }
		[                         DataMember] public char   Gender     { get; set; }

		// FK_Doctor_Person_BackReference
		[Association(ThisKey="PersonID", OtherKey="PersonID", CanBeNull=true)]
		public Doctor Doctor { get; set; }

		// FK_Patient_Person_BackReference
		[Association(ThisKey="PersonID", OtherKey="PersonID", CanBeNull=true)]
		public Patient Patient { get; set; }
	}
}
