//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;
using BLToolkit.Mapping;

namespace Templates.PostgreSQL
{
	public partial class PostgreSQLDataModel : DbManager
	{
		public Table<child>         child         { get { return this.GetTable<child>();         } }
		public Table<grandchild>    grandchild    { get { return this.GetTable<grandchild>();    } }
		public Table<linqdatatypes> linqdatatypes { get { return this.GetTable<linqdatatypes>(); } }
		public Table<parent>        parent        { get { return this.GetTable<parent>();        } }
		public Table<person>        person        { get { return this.GetTable<person>();        } }
	}

	[TableName(Name="child")]
	public partial class child
	{
		[Nullable] public Int32? parentid { get; set; }
		[Nullable] public Int32? childid  { get; set; }
	}

	[TableName(Name="grandchild")]
	public partial class grandchild
	{
		[Nullable] public Int32? parentid     { get; set; }
		[Nullable] public Int32? childid      { get; set; }
		[Nullable] public Int32? grandchildid { get; set; }
	}

	[TableName(Name="linqdatatypes")]
	public partial class linqdatatypes
	{
		[Nullable] public Int32?    id            { get; set; }
		[Nullable] public Decimal?  moneyvalue    { get; set; }
		[Nullable] public DateTime? datetimevalue { get; set; }
		[Nullable] public Boolean?  boolvalue     { get; set; }
		[Nullable] public Guid?     guidvalue     { get; set; }
		           public Byte[]    binaryvalue   { get; set; }
		[Nullable] public Int16?    smallintvalue { get; set; }
	}

	[TableName(Name="parent")]
	public partial class parent
	{
		[Nullable] public Int32? parentid { get; set; }
		[Nullable] public Int32? value1   { get; set; }
	}

	[TableName(Name="person")]
	public partial class person
	{
		[Identity, PrimaryKey(1)] public Int32  personid   { get; set; }
		                          public String firstname  { get; set; }
		                          public String lastname   { get; set; }
		                          public String middlename { get; set; }
		                          public String gender     { get; set; }
	}
}
